scheduler:
  delay: 30000

mail:
  protocol: "imaps"
  host: localhost
  port: 993
  user: guest
  password: guest
  tlsEnabled: true

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest